### ISSUE TITLE
Could I run MU-Net on T-1w mouse brain?

### ISSUE THREAD

**Issue by anqu1002** [Hierakonpolis/MU-Net#1]
Hi Riccardo De Feo,

I tried to run your MU-Net on some mouse T1-w images, but I couldn't get the skull stripping and segmentation results. The input file hasn't been overwritten.

The command I used is: python3 runMU-Net.py path/to/input/image --overwrite True

Then I got the following log info:
![ask](https://user-images.githubusercontent.com/21129893/79271045-29709300-7e6d-11ea-8e23-51fb58413caf.png)

I noticed that the MU-Net is trained from a bunch of mouse T-2w images, would my T-1w input image be a problem? Besides, I don't understand the warning message and I didn't find any flag in the usage documentation that is relevant to specify the term, brain volume for sample.

Thanks for your time in advance!

**Comment by Hierakonpolis** [comment]
Hello!
System trained for MRI data can be highly specialized, even for something
like the specific coil or manufacturers, but if we're talking about a
completely different contrast the system was not trained on there is little
doubt it will not work. That warning indicates the preliminary step to find
the bounding box failed. Thank you for taking your time to contact me, I
can at least improve that warning.

**Comment by anqu1002** [comment]
Thanks Riccardo for the fast and detailed reply. Really appreciated!
