### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by mmlitvak** [Hierakonpolis/MU-Net#2]
We are interested in using your algorithm in our research. I successfully installed all the software as instructed, but I wasn't able to achieve any result. Could you please provide a bit more detailed instructions on how to run it. Thanks in advance!

**Comment by Hierakonpolis** [comment]
Did it fail to run, or did it fail to generate a meaningful output?
If the latter is true, can you give me any details about your data?

**Comment by mmlitvak** [comment]
It appears to be running. But  nothing happens. No errors, no confirmation. No new files added and old files rewrites. 
![anaconda](https://user-images.githubusercontent.com/68888827/88648205-6f293280-d0cf-11ea-8833-71e49062cacf.jpg)

**Comment by mmlitvak** [comment]
We have mouse brain in DICOM that has been transferred to nifti format by MRIcroGL 1.2.2

**Comment by mmlitvak** [comment]
[https://github.com/mmlitvak/MRI_M2](url)

**Comment by Hierakonpolis** [comment]
I tried segmenting that volume and the program seems to run. Have you tried using the full path for your target volume?
On the other hand, I am quite sure these images look different enough that it will be difficult to obtain a meaningful output. However, if you have a small number of labeled volumes it would not be hard to retrain MU-Net to adapt it to your target volumes.

**Comment by mmlitvak** [comment]
Yes. I tried full path. Unfortunately I don't know how properly running program should look like. Should it open *.nii images after it was started or save segmented images automatically? Maybe run it with FSL or MathLab?

**Comment by Hierakonpolis** [comment]
It should look something like this:
![Untitled](https://user-images.githubusercontent.com/35005069/88661285-efa45f00-d0e0-11ea-96e1-4cb2503e3b55.png)

It's really strange that we simply do not get any error in your case. I changed a few lines in the code which might help with compatibility with windows systems, could you please update the code (git pull) and try again?

**Comment by mmlitvak** [comment]
I just did and nothing changed. I'll try to reinstall it under Linux

**Comment by Hierakonpolis** [comment]
I managed to get a hold of a windows machine. Have you tried making sure your python executable is indeed python3? 

It might simply be called python:
`python runMU-Net.py`

**Comment by mmlitvak** [comment]
Thanks! Now it seems to be working! But I've found that NVIDIA card is missing on my machine. Is it crucial to have it? I've tried useGPU False, but this did not help.
![nvidia_needed](https://user-images.githubusercontent.com/68888827/88792927-b03f4680-d1a4-11ea-96cd-b9de6aab83a8.jpg)

**Comment by Hierakonpolis** [comment]
Can you please update and try again?

**Comment by Hierakonpolis** [comment]
Current version seems to work without GPU support, closing this issue.

**Comment by mmlitvak** [comment]
It worked! Thanks! Unfortunately we weren't able to achieve any valuable segmentation. Maybe the problem is in our MRI machine setup. Any specific recommendations?

**Comment by Hierakonpolis** [comment]
That is very likely, what is your MRI setup? Scanners from different
vendors can produce data distributed in a significantly different way, and
even choosing a different coil can significantly alter the overall visual
outlook of the image, so these are all complicating factors.
However, we can consider retraining the network. Depending on your data it
could take a limited amount of labeled samples (even something like 5-10)
and it might be a good investment if you have a large number of volumes to
label.

Il giorno mar 4 ago 2020 alle ore 09:01 mmlitvak <notifications@github.com>
ha scritto:

**Comment by mmlitvak** [comment]
We would really appreciate if you will be able to train your network based our MRI setup (I have 7 mice in vivo MRI  of quite good quality) or please, provide an instruction how to do so. Thanks in advance!

**Comment by Hierakonpolis** [comment]
Is 7 the total amount of mice you want to label? Retraining the network
requires data. Perhaps a small number of samples, but we would need some
data to be already labeled. If you have a large number of mice to process,
now or in the future, it might well be worth the effort. Before looking for
a different way to adapt this, if you only have 7 scans to process and no
future plans for more of them, it might make more sense to use atlas-based
segmentation and manually correct some mistakes. If you plan to add more
scans to your study, these could later be used to then train a network and
scale it to the hundreds of mice.

On our github page you can find a link to a tutorial on how to train a
similar network (on publicly available data) if you are interested, and I
would be happy to work with you and provide a straightforward way to easily
train this network, but let's try to make sure this is also the correct
course of action for your specific situation.

Il giorno mar 4 ago 2020 alle ore 11:53 mmlitvak <notifications@github.com>
ha scritto:
