### ISSUE TITLE
Trouble using segmenter.py as well as runMU-Net.py

### ISSUE THREAD

**Issue by js-kki** [Hierakonpolis/MU-Net#4]
Hello, I have run into trouble when attempting to use the runners from MU-Net as well as MU-Net-R. I have axial volumes, (25x128x128), and attempted to use the pre-trained models in MU-Net-R to run segmenter.py on these scans. The outputs, when loaded in, contained zeroes except for ones at the bound indices. When attempting to add the --train flag, I wasn't sure how to incorporate all of my .nii files to train the model on. I then tried running runMU-Net.py as the function call was much more straight-forward, but it failed to create boundingboxes on my axial vols. I also tried transposing the data to a different axis and tried again to no avail. Out of curiosity, I then tried to run runMU-Net.py on the NN4Kubiac/TutorialMUNet/in_vivo/templates/ vols but that too failed to create boundingboxes. I feel as though I'm doing something wrong on the command line, but I'm unsure how to proceed. Any tips would be fantastic!

**Comment by Hierakonpolis** [comment]
From the readme:

To train this on your data we recommend using the scripts found in our more recent release MU-Net-R.

https://github.com/Hierakonpolis/MU-Net-R

This should be easier to use. Because there is a more recent version, I don't really plan on offering any support for the older one.

**Comment by js-kki** [comment]
I attempted the use of MU-Net-R prior to MU-Net. I'll open up the issue there and write about what I tried. Thank you for the help.
